### ISSUE TITLE
Add port for INT line from current sensor

### ISSUE THREAD

**Issue by chaseblock** [lhr-solar/BPS-LeaderPCB#1]
See lhr-solar/BPS-AmperesPCB#1. I think it would be neat to handle current sensing off-board (at least most of the time). Not required though.

**Comment by chaseblock** [comment]
One possible issue would be a disconnect: we would have to check in with the board regularly still, but it would hopefully allow us to do that at a slower rate.

If we fashioned an interrupt to a loopback connection of some sort, then we may not even have to check in with the board except when we see that we are getting close to our limit.

**Comment by ClarkPoon** [comment]
Closing this issue because we no longer use a current sensor with an interrupt line
